# Config file for automatic testing at travis-ci.org

language: python

sudo: false

env:
    - TOX_ENV=py27-coverage-init
    - TOX_ENV=py27-django17
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-djangomaster
    - TOX_ENV=py34-django17
    - TOX_ENV=py34-django18
    - TOX_ENV=py34-djangomaster
    - TOX_ENV=py27-coverage-report
    - TOX_ENV=py27-lint
    - TOX_ENV=py27-isort
    global:
        - DISPLAY=:99.0

matrix:
    fast_finish: true
    allow_failures:
        - env: TOX_ENV=py27-djangomaster
        - env: TOX_ENV=py34-djangomaster

install:
    - pip install tox

script:
    - tox -e $TOX_ENV

before_install:
    - pip install codecov
    - "/sbin/start-stop-daemon --start --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
    - sleep 3 # give xvfb some time to start

after_success:
    - codecov
